### GET /

GET http://localhost:5003

### POST register user

POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}

### POST login user

POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}
